# Generated by Django 6.0.4 on 2026-04-24 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('stopwatch', 'Kronometre'), ('short_break', 'Kısa Mola'), ('long_break', 'Uzun Mola')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='Ders adı veya çalışma başlığı', max_length=255)),
                ('planned_duration_minutes', models.PositiveIntegerField(default=25, help_text='Planlanan süre (dakika). Kronometre için 0.')),
                ('actual_duration_seconds', models.PositiveIntegerField(default=0, help_text='Gerçek çalışma süresi (saniye).')),
                ('started_at', models.DateTimeField(help_text='Oturumun başladığı zaman.')),
                ('ended_at', models.DateTimeField(help_text='Oturumun bittiği zaman.')),
                ('completed', models.BooleanField(default=False, help_text='Oturum tamamlandı mı (süre doldu) yoksa erken mi durduruldu.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-ended_at'],
                'indexes': [models.Index(fields=['user', 'session_type'], name='pomodoro_se_user_id_ed50b8_idx'), models.Index(fields=['user', 'ended_at'], name='pomodoro_se_user_id_dc2c0d_idx'), models.Index(fields=['user', 'title'], name='pomodoro_se_user_id_16d2ef_idx')],
            },
        ),
    ]
