# Generated by Django 6.0.2 on 2026-04-14 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focussession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='focussession',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='focussession',
            name='category',
            field=models.CharField(default='Genel Çalışma', max_length=100),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
